language: node_js

node_js:
 - "8"
 - "10"
 # FIXME: something is precluding perseo-fe to work in Node v12. Some tests are failing
 #- "12"

branches:
  only:
    - master

services:
 - mongodb

addons:
  apt:
    sources:
    - mongodb-3.6-precise
    packages:
    - mongodb-org-server

install:
 - npm install

before_install:
 - npm update -q

before_script:
 - npm run lint
# - npm run lint:text
 - npm run lint:md

after_script: 
  - npm run test:coveralls

